name = "nlp_parser_v7"
version = "0.1.0"
license = "CC0-1.0"
author = "Loren"
maintainer = "Loren"
copyright = "2026"
[build]
auto-executables = true
auto-tests = false
auto-examples = false

[dependencies]
json-fortran.git = "https://github.com/jacobwilliams/json-fortran.git"
